[project]
authors = ["mikedecr <mgdecrescenzo@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mandelbrot-recursive"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
quarto = "1.6.*"
r-base = ">=4.4.3,<4.5"
r-dplyr = ">=1.1.4,<2"
r-rmarkdown = ">=2.29,<3"
r-tidyr = ">=1.3.1,<2"
r-ggplot2 = ">=3.5.2,<4"
